trigger:
- main

pr:
- main

pool: ExamplePool

stages:
  - stage: Dev
    jobs:
    - template: templates/terraform.yaml
      parameters:
        environment: dev
        workingDirectory: $(System.DefaultWorkingDirectory)
  - stage: Prod
    dependsOn: Dev
    jobs:
    - template: templates/terraform.yaml
      parameters:
        environment: prod
        workingDirectory: $(System.DefaultWorkingDirectory)
    
