# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@2
  inputs:
    terraformVersion: '1.10.5'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Jan2025PlatformsAcademy'
    backendAzureRmKey: 'ajb-azure-exercise/dev/terraform.tfstate'
    allowTelemetryCollection: true