trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev
    jobs:
    - template: templates/terraform.yaml
      parameters:
        environment: dev
        workingDirectory: $(Pipeline.Workspace)
  - stage: Prod
    dependsOn: Dev
    jobs:
    - template: templates/terraform.yaml
      parameters:
        environment: prod
        workingDirectory: $(Pipeline.Workspace)
    
